#!/usr/bin/env bash
# display information about subdomains.
cutinfo() {
    DIGOUT=$(dig "$MYURL" | grep -A1 'ANSWER SECTION:' | tail -1)
    RTYPE=$(echo "$DIGOUT" | awk '{print $4}')
    IP=$(echo "$DIGOUT" | awk '{print $5}')
}
if [ $# -eq 2 ]
then
    MYURL="$2.$1"
    cutinfo "$MYURL"
    echo "The subdomain $2 is a $RTYPE record and points to $IP"
elif [ $# -eq 1 ]
then
    MYLIST=('www' 'lb-01' 'web-01' 'web-02')
    for subd in "${MYLIST[@]}"
    do
        MYURL="$subd.$1"
        cutinfo "$MYURL"
        echo "The subdomain $subd is a $RTYPE record and points to $IP"
    done
fi
