#!/bin/bash
export WATER="ewwatratewa";
export STIR="ti.itirtrtr";
PASSWORD="behlnort";
WATERB5=$(echo $WATER | tr water 01234);
STIRB5=$(echo $STIR | tr stir. 01234);
WATERB10=$((5#$WATERB5));
STIRB10=$((5#$STIRB5));
ANSWER=$(($WATERB10+$STIRB10));
ANSWERB8=$(echo printf "%o\n" $ANSWER);
$ANSWERB8 | tr 01234567 $PASSWORD
