#!/bin/bash
PASSWORD="behlnort";
WATER=$(echo $WATER | tr water 01234);
STIR=$(echo $STIR | tr stir. 01234);
WATER=$((5#$WATER));
STIR=$((5#$STIR));
ANSWER=$(($WATER+$STIR));
$(echo printf '%o\n' $ANSWER)| tr 01234567 $PASSWORD
