#!/bin/bash
PASSWORD="behlnort";
WATERB5=$(echo $WATER | tr water 01234);
STIRB5=$(echo $STIR | tr stir. 01234);
WATERB10=$((5#$WATERB5));
STIRB10=$((5#$STIRB5));
ANSWER=$(($WATERB10+$STIRB10));
WATER=$WATER;
STIR=$STIR;
ANSWERB8=$(echo printf '%o\n' $ANSWER);
$ANSWERB8 | tr 01234567 $PASSWORD
