#!/usr/bin/env bash
# Install nginx web server
# /usr/share/nginx/html/index.html in ubuntu 14.04

sudo apt-get update &&
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo 'Holberton School' > /var/www/html/index.html
service nginx start
