#!/usr/bin/env bash
# if my domain have /redirect_me else redirect to another page.

sudo apt-get update &&
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo 'Holberton School' > /var/www/html/index.html
sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com permanent;' /etc/nginx/sites-available/default
service nginx start
