#!/usr/bin/env bash
# if not found the page render my 404page
# sudo nginx -t; sudo service nginx restart; //for apply changes

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo 'Holberton School' > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo sed -i '/listen 80 default_server/a error_page 404 /404.html; location = /404.html {root /var/www/html;\n internal;}' /etc/nginx/sites-available/default
service nginx start
