#!/usr/bin/env bash
# 1. install nginx
# 2. rewrite homepage and 404.html
# 3. Nginx is configured so that its HTTP response contains a custom header
# 4. Nginx is configured to redirect the page to another
# 5. if not found the page render my 404page
# 6. start nginx service
# pd: sudo nginx -t; sudo service nginx restart; //for apply changes

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo 'Holberton School' > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
sudo sed -i "/listen 80 default_server/a add_header X-Served-By '$HOSTNAME';" /etc/nginx/sites-available/default
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo sed -i '/listen 80 default_server/a error_page 404 /404.html; location = /404.html {root /var/www/html;\n internal;}' /etc/nginx/sites-available/default
service nginx start
