#!/usr/bin/env bash
# HAproxy -> lb-01 server.

sudo apt-get -y update
sudo apt-get -y install haproxy
echo "ENABLED=1" >> /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg .
cat >> /etc/haproxy/haproxy.cfg << MYLIMIT
frontend front
	bind *:80
	mode http
	default_backend back
backend back
    balance roundrobin
    server 1293-web-01 34.228.37.117:80 check
    server 1293-web-02 54.234.227.98:80 check
MYLIMIT
sudo service haproxy restart
