#!/usr/bin/env bash
# pending
i=0
while ((i<20))
do
	let "i+=1"
	case $i in
		5) echo "bad luck from China";;
		10) echo "bad luck from Japan";;
		18) echo "bad luck from Italy";;
	esac
	echo "$i"
done
